### ISSUE TITLE
GitHub link on https://hygames.dev redirects to https://github.com/hygames-team

### ISSUE THREAD

**Issue by ghost** [hygames-team/www-hygames-co#5]
GitHub link on `https://hygames.dev` home page redirects to `https://github.com/hygames-team` but was expected to redirect to `https://github.com/hygames`.

**Comment by NiklasEi** [comment]
Thanks :)

**Comment by NiklasEi** [comment]
Closed in 9630260fca6cb568b3ffdf01eaf619d8ac7d119b
